import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'How Swaparr collects, uses, and protects your information.',
};

export default function PrivacyPage() {
  return (
    <div className="legal-page">
      <header className="legal-header">
        <Link href="/" className="legal-logo">
          <span className="logo-mark" style={{ width: 28, height: 28, fontSize: 11 }}>SW</span>
          <span className="logo-wordmark" style={{ fontSize: 16 }}>Swaparr</span>
        </Link>
      </header>

      <main className="legal-content">
        <h1>Privacy Policy</h1>
        <p className="legal-date">Last updated: July 2026</p>

        <p>Swaparr (&ldquo;we&rdquo;, &ldquo;our&rdquo;, &ldquo;the platform&rdquo;) is a local barter marketplace based in Amman, Jordan. This policy explains what information we collect, how we use it, and your rights.</p>

        <h2>1. Information We Collect</h2>
        <p>When you use Swaparr we collect:</p>
        <ul>
          <li><strong>Account information</strong> — your display name and email address when you register.</li>
          <li><strong>Listings</strong> — photos, titles, descriptions, and item categories you submit when posting an item.</li>
          <li><strong>Messages</strong> — the content of conversations you have with other users on the platform.</li>
          <li><strong>Activity</strong> — items you like, trade offers you send or receive, and matches generated by your listings.</li>
        </ul>

        <h2>2. How We Use Your Information</h2>
        <ul>
          <li>To create and maintain your account.</li>
          <li>To display your listings to other users and surface relevant matches.</li>
          <li>To deliver messages and trade offer notifications between users.</li>
          <li>To improve the platform and fix bugs.</li>
        </ul>
        <p>We do not sell your personal information to third parties.</p>

        <h2>3. Data Storage &amp; Security</h2>
        <p>Your data is stored securely using <strong>Supabase</strong>, a hosted Postgres database provider. Supabase applies industry-standard encryption at rest and in transit. Images are stored in Supabase Storage.</p>

        <h2>4. Data Sharing</h2>
        <p>We share your information only:</p>
        <ul>
          <li>With other Swaparr users, to the extent necessary to facilitate trades (e.g., your display name appears on your listings and messages).</li>
          <li>With service providers (Supabase, Vercel) who help us operate the platform, under confidentiality obligations.</li>
          <li>When required by Jordanian law or a valid legal process.</li>
        </ul>

        <h2>5. Your Rights</h2>
        <p>You may request to access, correct, or delete your account data at any time by contacting us at <a href="mailto:hello@swappr.jo">hello@swappr.jo</a>. We will respond within 30 days.</p>

        <h2>6. Cookies &amp; Local Storage</h2>
        <p>Swaparr uses browser local storage to keep you signed in and remember your session preferences. We do not use third-party advertising cookies.</p>

        <h2>7. Children</h2>
        <p>Swaparr is not directed at children under 13. If you believe a child has created an account, please contact us and we will delete it promptly.</p>

        <h2>8. Changes to This Policy</h2>
        <p>We may update this policy from time to time. We will notify users of material changes by updating the date at the top of this page.</p>

        <h2>9. Contact</h2>
        <p>Questions? Reach us at <a href="mailto:hello@swappr.jo">hello@swappr.jo</a>.</p>
      </main>

      <footer className="legal-footer">
        <p>&copy; 2026 Swaparr &mdash; Built in Amman, for Amman.</p>
        <div className="legal-footer-links">
          <Link href="/privacy">Privacy Policy</Link>
          <Link href="/terms">Terms of Service</Link>
        </div>
      </footer>
    </div>
  );
}
